# Copyright NTU CSIE CMLAB 2005 - 2012
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file ../../../../LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

SRCS = exr.cpp jpeg.cpp png.cpp tiff.cpp crw.cpp hdr.cpp bmp.cpp
OBJS = ${SRCS:.cpp=.o} dcraw.o

clean:
	rm -f $(OBJS) *.gch *.core
